import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: ['./src/index.ts'],
  shims: true,
  format: 'esm',
  dts: true,
  clean: true,
  attw: true,
  deps: {
    onlyBundle: false,
    neverBundle: [
      '@antfu/eslint-config',
      '@antfu/install-pkg',
      '@clack/prompts',
      '@e18e/eslint-plugin',
      '@eslint-community/eslint-plugin-eslint-comments',
      '@eslint/markdown',
      '@eslint/config-helpers',
      '@stylistic/eslint-plugin',
      '@typescript-eslint/eslint-plugin',
      '@typescript-eslint/parser',
      '@typescript-eslint/types',
      '@typescript-eslint/utils',
      '@typescript-eslint/typescript-estree',
      '@vitest/eslint-plugin',
      'ansis',
      'cac',
      'eslint',
      '@types/eslint',
      'eslint-config-flat-gitignore',
      'eslint-flat-config-utils',
      'eslint-merge-processors',
      'eslint-plugin-antfu',
      'eslint-plugin-command',
      'eslint-plugin-import-lite',
      'eslint-plugin-jsdoc',
      'eslint-plugin-jsonc',
      'eslint-plugin-n',
      'eslint-plugin-no-only-tests',
      'eslint-plugin-perfectionist',
      'eslint-plugin-pnpm',
      'eslint-plugin-regexp',
      'eslint-plugin-toml',
      'eslint-plugin-unicorn',
      'eslint-plugin-unused-imports',
      'eslint-plugin-vue',
      'eslint-plugin-yml',
      'eslint-processor-vue-blocks',
      'globals',
      'local-pkg',
      'parse-gitignore',
      'toml-eslint-parser',
      'vue-eslint-parser',
      'yaml-eslint-parser',
      'find-up-simple',
    ],
  },
});
