import { GLOB_SRC, GLOB_SRC_EXT } from '../globs';

import type { TypedFlatConfigItem } from '../types';

export function disables(): TypedFlatConfigItem[] {
  return [
    {
      files: [`**/scripts/${GLOB_SRC}`],
      name: 'svifty7/disables/scripts',
      rules: {
        'antfu/no-top-level-await': 'off',
        'no-console': 'off',
        'ts/explicit-function-return-type': 'off',
      },
    },
    {
      files: [`**/cli/${GLOB_SRC}`, `**/cli.${GLOB_SRC_EXT}`],
      name: 'svifty7/disables/cli',
      rules: {
        'antfu/no-top-level-await': 'off',
        'no-console': 'off',
      },
    },
    {
      files: ['**/bin/**/*', `**/bin.${GLOB_SRC_EXT}`],
      name: 'svifty7/disables/bin',
      rules: {
        'antfu/no-import-dist': 'off',
        'antfu/no-import-node-modules-by-path': 'off',
      },
    },
    {
      files: ['**/*.d.?([cm])ts'],
      name: 'svifty7/disables/dts',
      rules: {
        'eslint-comments/no-unlimited-disable': 'off',
        'import/no-duplicates': 'off',
        'no-restricted-syntax': 'off',
        'unused-imports/no-unused-vars': 'off',
      },
    },
    {
      files: ['**/*.js', '**/*.cjs'],
      name: 'svifty7/disables/cjs',
      rules: {
        'ts/no-require-imports': 'off',
      },
    },
    {
      files: [`**/*.config.${GLOB_SRC_EXT}`, `**/*.config.*.${GLOB_SRC_EXT}`],
      name: 'svifty7/disables/config-files',
      rules: {
        'antfu/no-top-level-await': 'off',
        'no-console': 'off',
        'ts/explicit-function-return-type': 'off',
      },
    },
    {
      name: 'svifty7/disables/prettier',
      rules: {
        'no-unexpected-multiline': 'off',
        'style/array-bracket-newline': 'off',
        'style/array-bracket-spacing': 'off',
        'style/array-element-newline': 'off',
        'style/arrow-parens': 'off',
        'style/arrow-spacing': 'off',
        'style/block-spacing': 'off',
        'style/brace-style': 'off',
        'style/comma-dangle': 'off',
        'style/comma-spacing': 'off',
        'style/comma-style': 'off',
        'style/computed-property-spacing': 'off',
        'style/dot-location': 'off',
        'style/eol-last': 'off',
        'style/func-call-spacing': 'off',
        'style/function-call-argument-newline': 'off',
        'style/function-call-spacing': 'off',
        'style/function-paren-newline': 'off',
        'style/generator-star-spacing': 'off',
        'style/implicit-arrow-linebreak': 'off',
        'style/indent': 'off',
        'style/indent-binary-ops': 'off',
        'style/jsx-child-element-spacing': 'off',
        'style/jsx-closing-bracket-location': 'off',
        'style/jsx-closing-tag-location': 'off',
        'style/jsx-curly-newline': 'off',
        'style/jsx-curly-spacing': 'off',
        'style/jsx-equals-spacing': 'off',
        'style/jsx-first-prop-new-line': 'off',
        'style/jsx-indent-props': 'off',
        'style/jsx-max-props-per-line': 'off',
        'style/jsx-newline': 'off',
        'style/jsx-one-expression-per-line': 'off',
        'style/jsx-props-no-multi-spaces': 'off',
        'style/jsx-quotes': 'off',
        'style/jsx-tag-spacing': 'off',
        'style/jsx-wrap-multilines': 'off',
        'style/key-spacing': 'off',
        'style/keyword-spacing': 'off',
        'style/linebreak-style': 'off',
        'style/lines-around-comment': 'off',
        'style/max-len': 'off',
        'style/max-statements-per-line': 'off',
        'style/member-delimiter-style': 'off',
        'style/multiline-ternary': 'off',
        'style/new-parens': 'off',
        'style/newline-per-chained-call': 'off',
        'style/no-confusing-arrow': 'off',
        'style/no-extra-parens': 'off',
        'style/no-extra-semi': 'off',
        'style/no-floating-decimal': 'off',
        'style/no-mixed-operators': 'off',
        'style/no-mixed-spaces-and-tabs': 'off',
        'style/no-multi-spaces': 'off',
        'style/no-multiple-empty-lines': 'off',
        'style/no-tabs': 'off',
        'style/no-trailing-spaces': 'off',
        'style/no-whitespace-before-property': 'off',
        'style/nonblock-statement-body-position': 'off',
        'style/object-curly-newline': 'off',
        'style/object-curly-spacing': 'off',
        'style/object-property-newline': 'off',
        'style/one-var-declaration-per-line': 'off',
        'style/operator-linebreak': 'off',
        'style/padded-blocks': 'off',
        'style/quote-props': 'off',
        'style/quotes': 'off',
        'style/rest-spread-spacing': 'off',
        'style/semi': 'off',
        'style/semi-spacing': 'off',
        'style/semi-style': 'off',
        'style/space-before-blocks': 'off',
        'style/space-before-function-paren': 'off',
        'style/space-in-parens': 'off',
        'style/space-infix-ops': 'off',
        'style/space-unary-ops': 'off',
        'style/switch-colon-spacing': 'off',
        'style/template-curly-spacing': 'off',
        'style/template-tag-spacing': 'off',
        'style/type-annotation-spacing': 'off',
        'style/type-generic-spacing': 'off',
        'style/type-named-tuple-spacing': 'off',
        'style/wrap-iife': 'off',
        'style/wrap-regex': 'off',
        'style/yield-star-spacing': 'off',
        'unicorn/empty-brace-spaces': 'off',
        'unicorn/no-nested-ternary': 'off',
        'unicorn/number-literal-case': 'off',
        'unicorn/template-indent': 'off',
        'vue/array-bracket-newline': 'off',
        'vue/array-bracket-spacing': 'off',
        'vue/array-element-newline': 'off',
        'vue/arrow-spacing': 'off',
        'vue/block-spacing': 'off',
        'vue/block-tag-newline': 'off',
        'vue/brace-style': 'off',
        'vue/comma-dangle': 'off',
        'vue/comma-spacing': 'off',
        'vue/comma-style': 'off',
        'vue/dot-location': 'off',
        'vue/func-call-spacing': 'off',
        'vue/html-closing-bracket-newline': 'off',
        'vue/html-closing-bracket-spacing': 'off',
        'vue/html-end-tags': 'off',
        'vue/html-indent': 'off',
        'vue/html-quotes': 'off',
        'vue/html-self-closing': 'off',
        'vue/key-spacing': 'off',
        'vue/keyword-spacing': 'off',
        'vue/max-attributes-per-line': 'off',
        'vue/max-len': 'off',
        'vue/multiline-html-element-content-newline': 'off',
        'vue/multiline-ternary': 'off',
        'vue/mustache-interpolation-spacing': 'off',
        'vue/no-extra-parens': 'off',
        'vue/no-multi-spaces': 'off',
        'vue/no-spaces-around-equal-signs-in-attribute': 'off',
        'vue/object-curly-newline': 'off',
        'vue/object-curly-spacing': 'off',
        'vue/object-property-newline': 'off',
        'vue/operator-linebreak': 'off',
        'vue/quote-props': 'off',
        'vue/script-indent': 'off',
        'vue/singleline-html-element-content-newline': 'off',
        'vue/space-in-parens': 'off',
        'vue/space-infix-ops': 'off',
        'vue/space-unary-ops': 'off',
        'vue/template-curly-spacing': 'off',
      },
    },
  ];
}
