import type { TypedFlatConfigItem } from '@antfu/eslint-config';

export function stylistic(): TypedFlatConfigItem {
  return {
    name: 'svifty7/stylistic/rules',
    rules: {
      'antfu/consistent-chaining': 'error',
      'antfu/consistent-list-newline': 'off',
      'antfu/curly': 'off',
      'antfu/if-newline': 'off',
      'antfu/top-level-function': 'error',

      'style/jsx-curly-brace-presence': 'off', // ts(7027)
      'style/jsx-self-closing-comp': 'off',
      'style/no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0, maxBOF: 0 }],
      'style/padding-line-between-statements': [
        'error',
        {
          blankLine: 'always',
          prev: [
            'block-like',
            'break',
            'class',
            'const',
            'debugger',
            'directive',
            'throw',
            'try',
            'function',
            'import',
            'cjs-import',
            'return',
            'continue',
          ],
          next: '*',
        },
        {
          blankLine: 'always',
          prev: '*',
          next: [
            'block-like',
            'break',
            'class',
            'const',
            'continue',
            'debugger',
            'directive',
            'return',
            'throw',
            'try',
            'export',
            'cjs-export',
            'function',
            'import',
            'cjs-import',
          ],
        },
        {
          blankLine: 'always',
          prev: '*',
          next: ['multiline-const', 'multiline-expression', 'multiline-let', 'multiline-var'],
        },
        {
          blankLine: 'always',
          prev: ['multiline-const', 'multiline-expression', 'multiline-let', 'multiline-var'],
          next: '*',
        },
        {
          blankLine: 'always',
          prev: 'block',
          next: 'block',
        },
        {
          blankLine: 'never',
          prev: 'break',
          next: ['case', 'default'],
        },
        {
          blankLine: 'never',
          prev: ['case', 'default'],
          next: ['case', 'default'],
        },
        {
          blankLine: 'any',
          prev: 'singleline-const',
          next: 'singleline-const',
        },
        {
          blankLine: 'any',
          prev: 'singleline-let',
          next: 'singleline-let',
        },
        {
          blankLine: 'any',
          prev: 'singleline-var',
          next: 'singleline-var',
        },
        {
          blankLine: 'any',
          prev: 'directive',
          next: 'directive',
        },
        {
          blankLine: 'any',
          prev: 'import',
          next: 'import',
        },
        {
          blankLine: 'any',
          prev: 'export',
          next: 'export',
        },
        {
          blankLine: 'any',
          prev: 'cjs-import',
          next: 'cjs-import',
        },
        {
          blankLine: 'any',
          prev: 'cjs-export',
          next: 'cjs-export',
        },
      ],
      'style/spaced-comment': ['error', 'always'],
      'style/lines-between-class-members': [
        'error',
        'always',
        { exceptAfterOverload: true, exceptAfterSingleLine: true },
      ],
      'style/operator-linebreak': ['error', 'before', {
        overrides: {
          '=': 'after',
          '+=': 'after',
          '-=': 'after',
          '*=': 'after',
          '/=': 'after',
          '%=': 'after',
          '**=': 'after',
          '&=': 'after',
          '|=': 'after',
          '^=': 'after',
          '<<=': 'after',
          '>>=': 'after',
          '>>>=': 'after',
        },
      }],
      'style/brace-style': ['error', '1tbs'],
      'style/arrow-parens': ['error', 'always'],
      'style/indent': ['error', 2, {
        SwitchCase: 1,
        VariableDeclarator: 1,
        outerIIFEBody: 1,
        MemberExpression: 1,
        FunctionDeclaration: { parameters: 1, body: 1 },
        FunctionExpression: { parameters: 1, body: 1 },
        CallExpression: { arguments: 1 },
        ArrayExpression: 1,
        ObjectExpression: 1,
        ImportDeclaration: 1,
        flatTernaryExpressions: false,
        offsetTernaryExpressions: true,
        ignoreComments: false,
      }],
      'style/object-curly-newline': ['error', {
        ObjectExpression: { multiline: true, consistent: true },
        ObjectPattern: { multiline: true, consistent: true },
        ImportDeclaration: { multiline: true, consistent: true },
        ExportDeclaration: { multiline: true, consistent: true },
      }],
      'style/object-property-newline': ['error', {
        allowAllPropertiesOnSameLine: true,
      }],
    },
  };
}
